// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "dino":return img`
........................
........................
..........ccc...........
.........cccc...........
.....ccccccc..ccc.......
...cc555555cccccc.......
..c5555555555bcc........
.c555555555555b..cc.....
c555551ff555555bccc.....
c55d55ff55555555bc......
c5555555555555555b......
.cbb31bb5555dd555b.cc...
.c5333b555ddddd55dccc...
.c533b55ddddddddddb.....
.c5555dddbb55bdddddccc..
..ccccbbbb555bdddddccc..
...cdcbc5555bddddddcc...
....ccbc55bc5ddddddbcccc
.....cbbcc5555dddddddddc
.....ccbbb555ddbddddddc.
.....cdcbc55ddbbbdddcc..
...ccdddccddddbcbbcc....
...ccccccd555ddccc......
........cccccccc........
`;
            case "image3":
            case "dino0":return img`
........................
........................
...........ccc..........
...........cccc.........
.......ccc..ccccccc.....
.......cccccc555555cc...
........ccb5555555555c..
.....cc..b555555555555c.
.....cccb555555ff155555c
......cb55555555ff55d55c
......b5555555555555555c
...cc.b555dd5555bb13bbc.
...cccd55ddddd555b3335c.
.....bdddddddddd55b335c.
..cccdddddb55bbddd5555c.
..cccdddddb555bbbbcccc..
...ccddddddb5555cbcdc...
ccccbdddddd5cb55cbcc....
cddddddddd5555ccbbc.....
.cddddddbdd555bbbcc.....
..ccdddbbbdd55cbcdc.....
....ccbbcbddddccdddcc...
......cccdd555dcccccc...
........cccccccc........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
